import pandas as pd
df = pd.read_csv("/content/students_dataset.csv")
print(df.head())
print(df.info())
print(df.isnull().sum())
df_clean = df.dropna()
print(df_clean)
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
df['Attendance'] = df['Attendance'].fillna(df['Attendance'].mean())
df['Age'] = df['Age'].astype(int)
df['Marks'] = df['Marks'].astype(int)
df['Attendance'] = df['Attendance'].astype(int)
print(df.drop_duplicates())
df['Passed'] = df['Passed'].map({'Yes': 1, 'No': 0})
print(df)
